# Generated by Django 5.1.1 on 2026-01-27 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='resident_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Resident_Name', models.CharField(max_length=25)),
                ('Resident_Age', models.PositiveIntegerField()),
                ('Resident_ID', models.PositiveIntegerField(unique=True)),
                ('Resident_Gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('Resident_DateOfBirth', models.DateField()),
                ('Resident_AdmissionDate', models.DateField()),
                ('Resident_Phone', models.CharField(max_length=15)),
                ('Resident_GuardianName', models.CharField(max_length=25)),
                ('Resident_GuardianPhone', models.CharField(max_length=15)),
                ('Resident_Photo', models.ImageField(blank=True, null=True, upload_to='ResidentsImages')),
            ],
        ),
        migrations.CreateModel(
            name='Resident_Health',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Physical_condition', models.TextField()),
                ('History', models.TextField()),
                ('Medication', models.TextField()),
                ('Doctor_Name', models.CharField(max_length=25)),
                ('Doctor_Appointment', models.DateTimeField()),
                ('Doctor_Contact', models.CharField(max_length=15)),
                ('resident', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='FallAnalysis_App.resident_detail')),
            ],
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Incident_type', models.CharField(choices=[('LI', 'Leg Injury'), ('HI', 'Head Injury'), ('AI', 'Arm Injury'), ('BI', 'Back Injury'), ('FI', 'Fracture'), ('SP', 'Sprain'), ('BR', 'Bruise'), ('CT', 'Cut / Laceration'), ('KN', 'Knee Injury'), ('HP', 'Hip Injury'), ('SH', 'Shoulder Injury'), ('NK', 'Neck Injury'), ('FA', 'Fall No Injury'), ('OT', 'Other')], max_length=10)),
                ('Incident_time', models.DateTimeField()),
                ('Incident_location', models.CharField(choices=[('RM', 'Resident Room'), ('BR', 'Bathroom'), ('HL', 'Hallway'), ('ST', 'Staircase'), ('DN', 'Dining Area'), ('GD', 'Garden / Outdoor'), ('LB', 'Lobby'), ('EL', 'Elevator'), ('WD', 'Ward'), ('NR', 'Nurse Station'), ('PT', 'Physiotherapy Room'), ('OT', 'Other')], max_length=2)),
                ('Injury_level', models.TextField()),
                ('Resident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='FallAnalysis_App.resident_detail')),
                ('Health_Record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents', to='FallAnalysis_App.resident_health')),
            ],
        ),
    ]
