# Generated by Django 5.1.1 on 2026-01-27 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FallAnalysis_App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='Incident_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='incident',
            name='Injury_level',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resident_detail',
            name='Resident_AdmissionDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resident_detail',
            name='Resident_DateOfBirth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resident_detail',
            name='Resident_GuardianName',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='resident_detail',
            name='Resident_GuardianPhone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='resident_detail',
            name='Resident_Phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='resident_health',
            name='Doctor_Appointment',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resident_health',
            name='Doctor_Contact',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='resident_health',
            name='Doctor_Name',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='resident_health',
            name='History',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resident_health',
            name='Medication',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resident_health',
            name='Physical_condition',
            field=models.TextField(blank=True, null=True),
        ),
    ]
